#!/bin/bash

#WIP
read -p WIP

if [ "$INC" != "" ]; then
Last_Version_Number=7.68
Version_Number=$(echo "$Last_Version_Number + $1" | bc -l)
sed -i s/$(echo $Last_Version_Number)/$(echo $Version_Number)/g docs/_layouts/default.html
sed -i s/$(echo $Last_Version_Number)/$(echo $Version_Number)/g docs/README.md
sed -i s/$(echo $Last_Version_Number)/$(echo $Version_Number)/g readme.md
sed -i s/$(echo $Last_Version_Number)/$(echo $Version_Number)/g Dockerfile
sed -i s/Last_Version_Number=$Last_Version_Number/Last_Version_Number=$Version_Number/g increment.sh
echo Version Incremented From v$Last_Version_Number To v$Version_Number
fi

$docker buildx create \
  --name $MODULE-builder --buildkitd-flags "--oci-worker-rootless=true" \
  --driver docker-container --driver-opt "network=host,default-load=true" --bootstrap --use

mkdir -p Results && pushd Results
  rm -f $MODULE.* readme.md
  cosign_run=$(echo "script -q -c 'cosign verify-attestation $source_loc \
    --certificate-oidc-issuer https://github.com/login/oauth --certificate-identity $SIGSTORE_USR \
    --type spdxjson > base.image.sig' /dev/null > base.image.attested")
  echo $cosign_run | bash || echo $cosign_run | bash || exit 1
popd

$docker buildx build --tag $MODULE $CROSS \
  --build-arg SOURCE_DATE_EPOCH=$source_date_epoch \
  --build-arg SOURCE=$source \
  --build-arg NODE_VERSION=$node_ver \
  --build-arg NVM_VERSION=$nvm_ver \
  --build-arg PNPM_VERSION=$pnpm_ver .

pushd Results
  cosign_run=$(echo "script -q -c 'cosign verify-attestation docker.io/$REPO/$MODULE:$rel_date \
    --certificate-oidc-issuer https://github.com/login/oauth --certificate-identity $SIGSTORE_USR \
    --type spdxjson > $MODULE.image.sig' /dev/null > $MODULE.image.attested")
  echo $cosign_run | bash || echo $cosign_run | bash || exit 1
popd

$docker run -it --cpus=$(nproc) \
  --network=name=host,\"driver-opt=network=host\" \
  --name $MODULE $CROSS \
  -e PNPM_HOME=/tmp/.pnpm-home \
  -e NPM_CONFIG_CACHE=/tmp/.npm-cache \
  -e SOURCE_DATE_EPOCH=$source_date_epoch \
  $MODULE $TEST $SIGNING_KEY

rm -r -f builds/release && mkdir -p builds/release
$docker cp signal-desktop:/Signal-Desktop/release/ builds/ && rm -r -f builds/release/linux-*
mv builds/release/release.sha512sum Results/release.sha512sum

if [ "$check_file" = "1" ]; then
  pushd builds/release/
    cp /tmp/release.last.sha512sum release.last.sha512sum
    sha512sum -c release.last.sha512sum
    rm -f /tmp/release.last.sha512sum && rm -f release.last.sha512sum
  popd
fi

echo "# Base Build System: $(uname -o) $(uname -r) $(uname -p) $(lsb_release -ds) $(lsb_release -cs) $(uname -v)"  >> builds/release/release.sha512sum
awk '{a[i++]=$0}END{for(j=0;j<i-2;j++)print a[j];print a[i-1];print a[i-2]}' builds/release/release.sha512sum > tmp && mv tmp builds/release/release.sha512sum
ls -la builds/release/
